(in-package :cl-user)
(load "gunu.lisp")


(let ((orbital-spaces '((H I J K L h1 h2 h3)
                        (P A B C D p1 p2 p3)
                        (G g)))
      (contraction-rules '(((H H) 0 1)
                           ((P P) 1 0)))
      (|_ H P H| '(_ (G H) (P H)))
      (|P H P H| '(_ (P H) (P H)))
      (|Vhhpp * Tpphh * Tpphh| '((V (i a) (j b))
                                 (T (c k) (d l))
                                 (T (p1 h1) (p2 h2))))
      (|Vhphp * Thp * Rh| '((V (J I) (A B))
                            (T (C K))
                            (R (G L)))))
  (macrolet ((assert-with-env (fun-applied value)
               `(assert
                 (equal
                  ,(concatenate 'list fun-applied '(:orbital-spaces
                                                    orbital-spaces
                                                    :contraction-rules
                                                    contraction-rules))
                  ,value))))
    (assert-with-env
     (find-contractions-in-product-by-target |P H P H| |Vhhpp * Tpphh * Tpphh|)
     '(((J L) (B D) (I K) (A C))
       ((J L) (B D) (A C) (I K))
       ((B D) (J L) (I K) (A C))
       ((B D) (J L) (A C) (I K))
       ((J H1) (B D) (I K) (A C))
       ((J H1) (B D) (A C) (I K))
       ((B P1) (J L) (I K) (A C))
       ((B P1) (J L) (A C) (I K))
       ((J H2) (B D) (I K) (A C))
       ((J H2) (B D) (A C) (I K))
       ((B P2) (J L) (I K) (A C))
       ((B P2) (J L) (A C) (I K))
       ((J H1) (B P1) (I K) (A C))
       ((J H1) (B P1) (A C) (I K))
       ((B P1) (J H1) (I K) (A C))
       ((B P1) (J H1) (A C) (I K))
       ((J H2) (B P1) (I K) (A C))
       ((J H2) (B P1) (A C) (I K))
       ((B P2) (J H1) (I K) (A C))
       ((B P2) (J H1) (A C) (I K))
       ((J H2) (B P2) (I K) (A C))
       ((J H2) (B P2) (A C) (I K))
       ((B P2) (J H2) (I K) (A C))
       ((B P2) (J H2) (A C) (I K))
       ((J L) (B C) (A D) (I K))
       ((B D) (J K) (I L) (A C))
       ((J H1) (B C) (A D) (I K))
       ((B P1) (J K) (I L) (A C))
       ((J H2) (B C) (A D) (I K))
       ((B P2) (J K) (I L) (A C))
       ((J H1) (B D) (I L) (A C))
       ((B P1) (J L) (A D) (I K))
       ((J H2) (B D) (I L) (A C))
       ((B P2) (J L) (A D) (I K))
       ((J H1) (B P1) (I L) (A C))
       ((J H1) (B P1) (A D) (I K))
       ((B P1) (J H1) (I L) (A C))
       ((B P1) (J H1) (A D) (I K))
       ((J H2) (B P1) (I L) (A C))
       ((J H2) (B P1) (A D) (I K))
       ((B P2) (J H1) (I L) (A C))
       ((B P2) (J H1) (A D) (I K))
       ((J H2) (B P2) (I L) (A C))
       ((J H2) (B P2) (A D) (I K))
       ((B P2) (J H2) (I L) (A C))
       ((B P2) (J H2) (A D) (I K))
       ((J L) (B C) (A P1) (I K))
       ((B D) (J K) (I H1) (A C))
       ((J H1) (B C) (A P1) (I K))
       ((B P1) (J K) (I H1) (A C))
       ((J H2) (B C) (A P1) (I K))
       ((B P2) (J K) (I H1) (A C))
       ((J L) (B D) (I H1) (A C))
       ((J L) (B D) (A P1) (I K))
       ((B D) (J L) (I H1) (A C))
       ((B D) (J L) (A P1) (I K))
       ((J H1) (B D) (A P1) (I K))
       ((B P1) (J L) (I H1) (A C))
       ((J H2) (B D) (I H1) (A C))
       ((J H2) (B D) (A P1) (I K))
       ((B P2) (J L) (I H1) (A C))
       ((B P2) (J L) (A P1) (I K))
       ((J H2) (B P1) (I H1) (A C))
       ((B P2) (J H1) (A P1) (I K))
       ((J H2) (B P2) (I H1) (A C))
       ((J H2) (B P2) (A P1) (I K))
       ((B P2) (J H2) (I H1) (A C))
       ((B P2) (J H2) (A P1) (I K))
       ((J L) (B C) (A P2) (I K))
       ((B D) (J K) (I H2) (A C))
       ((J H1) (B C) (A P2) (I K))
       ((B P1) (J K) (I H2) (A C))
       ((J H2) (B C) (A P2) (I K))
       ((B P2) (J K) (I H2) (A C))
       ((J L) (B D) (I H2) (A C))
       ((J L) (B D) (A P2) (I K))
       ((B D) (J L) (I H2) (A C))
       ((B D) (J L) (A P2) (I K))
       ((J H1) (B D) (I H2) (A C))
       ((J H1) (B D) (A P2) (I K))
       ((B P1) (J L) (I H2) (A C))
       ((B P1) (J L) (A P2) (I K))
       ((J H2) (B D) (A P2) (I K))
       ((B P2) (J L) (I H2) (A C))
       ((J H1) (B P1) (I H2) (A C))
       ((J H1) (B P1) (A P2) (I K))
       ((B P1) (J H1) (I H2) (A C))
       ((B P1) (J H1) (A P2) (I K))
       ((J H2) (B P1) (A P2) (I K))
       ((B P2) (J H1) (I H2) (A C))
       ((J K) (B C) (I L) (A D))
       ((J K) (B C) (A D) (I L))
       ((B C) (J K) (I L) (A D))
       ((B C) (J K) (A D) (I L))
       ((J H1) (B C) (I L) (A D))
       ((J H1) (B C) (A D) (I L))
       ((B P1) (J K) (I L) (A D))
       ((B P1) (J K) (A D) (I L))
       ((J H2) (B C) (I L) (A D))
       ((J H2) (B C) (A D) (I L))
       ((B P2) (J K) (I L) (A D))
       ((B P2) (J K) (A D) (I L))
       ((J H1) (B P1) (I L) (A D))
       ((J H1) (B P1) (A D) (I L))
       ((B P1) (J H1) (I L) (A D))
       ((B P1) (J H1) (A D) (I L))
       ((J H2) (B P1) (I L) (A D))
       ((J H2) (B P1) (A D) (I L))
       ((B P2) (J H1) (I L) (A D))
       ((B P2) (J H1) (A D) (I L))
       ((J H2) (B P2) (I L) (A D))
       ((J H2) (B P2) (A D) (I L))
       ((B P2) (J H2) (I L) (A D))
       ((B P2) (J H2) (A D) (I L))
       ((J K) (B C) (I H1) (A D))
       ((J K) (B C) (A P1) (I L))
       ((B C) (J K) (I H1) (A D))
       ((B C) (J K) (A P1) (I L))
       ((J L) (B C) (I H1) (A D))
       ((B D) (J K) (A P1) (I L))
       ((J H1) (B C) (A P1) (I L))
       ((B P1) (J K) (I H1) (A D))
       ((J H2) (B C) (I H1) (A D))
       ((J H2) (B C) (A P1) (I L))
       ((B P2) (J K) (I H1) (A D))
       ((B P2) (J K) (A P1) (I L))
       ((J H1) (B D) (A P1) (I L))
       ((B P1) (J L) (I H1) (A D))
       ((J H2) (B D) (A P1) (I L))
       ((B P2) (J L) (I H1) (A D))
       ((J H2) (B P1) (I H1) (A D))
       ((B P2) (J H1) (A P1) (I L))
       ((J H2) (B P2) (I H1) (A D))
       ((J H2) (B P2) (A P1) (I L))
       ((B P2) (J H2) (I H1) (A D))
       ((B P2) (J H2) (A P1) (I L))
       ((J K) (B C) (I H2) (A D))
       ((J K) (B C) (A P2) (I L))
       ((B C) (J K) (I H2) (A D))
       ((B C) (J K) (A P2) (I L))
       ((J L) (B C) (I H2) (A D))
       ((B D) (J K) (A P2) (I L))
       ((J H1) (B C) (I H2) (A D))
       ((J H1) (B C) (A P2) (I L))
       ((B P1) (J K) (I H2) (A D))
       ((B P1) (J K) (A P2) (I L))
       ((J H2) (B C) (A P2) (I L))
       ((B P2) (J K) (I H2) (A D))
       ((J H1) (B D) (A P2) (I L))
       ((B P1) (J L) (I H2) (A D))
       ((J H2) (B D) (A P2) (I L))
       ((B P2) (J L) (I H2) (A D))
       ((J H1) (B P1) (I H2) (A D))
       ((J H1) (B P1) (A P2) (I L))
       ((B P1) (J H1) (I H2) (A D))
       ((B P1) (J H1) (A P2) (I L))
       ((J H2) (B P1) (A P2) (I L))
       ((B P2) (J H1) (I H2) (A D))
       ((J K) (B C) (I H1) (A P1))
       ((J K) (B C) (A P1) (I H1))
       ((B C) (J K) (I H1) (A P1))
       ((B C) (J K) (A P1) (I H1))
       ((J L) (B C) (I H1) (A P1))
       ((J L) (B C) (A P1) (I H1))
       ((B D) (J K) (I H1) (A P1))
       ((B D) (J K) (A P1) (I H1))
       ((J H2) (B C) (I H1) (A P1))
       ((J H2) (B C) (A P1) (I H1))
       ((B P2) (J K) (I H1) (A P1))
       ((B P2) (J K) (A P1) (I H1))
       ((J L) (B D) (I H1) (A P1))
       ((J L) (B D) (A P1) (I H1))
       ((B D) (J L) (I H1) (A P1))
       ((B D) (J L) (A P1) (I H1))
       ((J H2) (B D) (I H1) (A P1))
       ((J H2) (B D) (A P1) (I H1))
       ((B P2) (J L) (I H1) (A P1))
       ((B P2) (J L) (A P1) (I H1))
       ((J H2) (B P2) (I H1) (A P1))
       ((J H2) (B P2) (A P1) (I H1))
       ((B P2) (J H2) (I H1) (A P1))
       ((B P2) (J H2) (A P1) (I H1))
       ((J K) (B C) (I H2) (A P1))
       ((J K) (B C) (A P2) (I H1))
       ((B C) (J K) (I H2) (A P1))
       ((B C) (J K) (A P2) (I H1))
       ((J L) (B C) (I H2) (A P1))
       ((J L) (B C) (A P2) (I H1))
       ((B D) (J K) (I H2) (A P1))
       ((B D) (J K) (A P2) (I H1))
       ((J H1) (B C) (I H2) (A P1))
       ((B P1) (J K) (A P2) (I H1))
       ((J H2) (B C) (A P2) (I H1))
       ((B P2) (J K) (I H2) (A P1))
       ((J L) (B D) (I H2) (A P1))
       ((J L) (B D) (A P2) (I H1))
       ((B D) (J L) (I H2) (A P1))
       ((B D) (J L) (A P2) (I H1))
       ((J H1) (B D) (I H2) (A P1))
       ((B P1) (J L) (A P2) (I H1))
       ((J H2) (B D) (A P2) (I H1))
       ((B P2) (J L) (I H2) (A P1))
       ((J H2) (B P1) (A P2) (I H1))
       ((B P2) (J H1) (I H2) (A P1))
       ((J K) (B C) (I H2) (A P2))
       ((J K) (B C) (A P2) (I H2))
       ((B C) (J K) (I H2) (A P2))
       ((B C) (J K) (A P2) (I H2))
       ((J L) (B C) (I H2) (A P2))
       ((J L) (B C) (A P2) (I H2))
       ((B D) (J K) (I H2) (A P2))
       ((B D) (J K) (A P2) (I H2))
       ((J H1) (B C) (I H2) (A P2))
       ((J H1) (B C) (A P2) (I H2))
       ((B P1) (J K) (I H2) (A P2))
       ((B P1) (J K) (A P2) (I H2))
       ((J L) (B D) (I H2) (A P2))
       ((J L) (B D) (A P2) (I H2))
       ((B D) (J L) (I H2) (A P2))
       ((B D) (J L) (A P2) (I H2))
       ((J H1) (B D) (I H2) (A P2))
       ((J H1) (B D) (A P2) (I H2))
       ((B P1) (J L) (I H2) (A P2))
       ((B P1) (J L) (A P2) (I H2))
       ((J H1) (B P1) (I H2) (A P2))
       ((J H1) (B P1) (A P2) (I H2))
       ((B P1) (J H1) (I H2) (A P2))
       ((B P1) (J H1) (A P2) (I H2))))
    ))
