name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  documentation:
    runs-on: ubuntu-latest
    env:
      WITH_SHELL: nix-shell /home/runner/work/arponen/arponen/shell.nix --run
    steps:
    - uses: actions/checkout@v2.3.4

    - name: pwd
      run: |
        pwd

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Configure
      run: |
        mkdir -p build && cd build
        ${WITH_SHELL} 'emacs --version'
        ${WITH_SHELL} 'sbcl --version'

    - name: html
      run: |
        make readme.html
        mv readme.html build/index.html

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
         branch: gh-pages
         folder: ./build/
