# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.3.4

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: sbcl
      run: nix-shell --run './tools/run-tests.sh sbcl'

    - name: ccl
      run: nix-shell --run './tools/run-tests.sh ccl'

    - name: ecl
      run: nix-shell --run './tools/run-tests.sh ecl'

    - name: clisp
      run: nix-shell --run './tools/run-tests.sh clisp'

    - name: clasp
      run: nix-shell --run './tools/run-tests.sh clasp'

    - name: gcl
      run: nix-shell --run './tools/run-tests.sh gcl'
